services:
  postgres-db:
    container_name: cashflow
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: cashflow_dev
      POSTGRES_PASSWORD: secure-p@sswords-R-long
      POSTGRES_DB: cashflow
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5419:5432"
volumes:
  postgresql_data:
    driver: local