package com.cashflow.game.constant;

import com.cashflow.game.model.Position;

public record Board() {

    public static final Position[] FAST_TRACK = new Position[]{
            new Position(Position.TYPES.DREAM, "Buy a Forest", "Stop the loss of ancient trees. Donate 1,000 acres of forest and create a nature walk for all to enjoy.", 250000f, null/*Asset.of("", Asset.TYPES.DREAM, Asset.SUB_TYPES.NO_SUB_TYPE, 250000f)*/),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Pro Team Box Seats", "License a 12 person private skybox booth with food and beverage service at your favorite team's stadium.", 200000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Ancient Asian Cities", "A private plane & private guide take you & 5 friends to the most remote spots of Asia... where no tourists have gone before.", 150000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Stock Market for Kids", "Fund a business & investment school for young capitalists, teaching them the basics of business. School includes a mini stock exchange run by the students.", 125000f, null),
            new Position(Position.TYPES.CHARITY, "Charity", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Yacht Racing", "You & your crew fly to Perth, Australia. Spend one week racing a 12-meter against the fastest boats in the world.", 150000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.CASHFLOW, "Ca$hflow Day", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Cannes Film Festival", "Party with the stars! Tour France, plus one week in Cannes rubbing elbows with celebrities. You even land a starring role!", 125000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Private Fishing Cabin on a Montana Lake", "Fish from the dock of this remote cabin. Enjoy 6 months of solitude. Use of float plane included.", 100000f, null),
            new Position(Position.TYPES.MISFORTUNE, "Tax Audit!", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Park Named After You", "Tear down abandoned warehouse & build new recreational park. Donate police sub-station for park safety.", 225000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Run for Mayor", "Your financial expertise spurs masses of people to beg you to lead the city. You run and, of course, win. This is the start of your Presidential race. Campaign costs you", 125000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "A Gift of Faith", "Your religious organization is growing by leaps & bounds. New buildings are needed. You donate...", 175000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Heli-Ski the Swiss Alps", "A winter of helicopter skiing by day and playing at the glamorous hot spots at night. A medieval castle is your accommodation.", 150000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Dinner with the President", "Buy a table for 10 friends to dine with the President at a gala ball for visiting dignitaries from around the world.", 100000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "A Research Center for Cancer & AIDS", "Your money brings together top researchers & doctors in one place, dedicated to eliminating these 2 diseases.", 225000f, null),
            new Position(Position.TYPES.CASHFLOW, "Ca$hflow Day", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "7 Wonders of the World", "Go by plane, boat, bicycle, camel, canoe & limo to the 7 Wonders of the World. First class luxury all the way!", 200000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Save the Ocean Mammals", "Fund & be a crew member on a month-long research expedition to protect endangered sea animals.", 125000f, null),
            new Position(Position.TYPES.MISFORTUNE, "Divorce!", "Lose all of your cash.", 0f, null),
            new Position(Position.TYPES.DREAM, "Be a \"Jet-Setter\"", "Have your own personal jet available for one year, to whisk you away whenever & wherever your heart desires.", 250000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Golf Around the World", "You take 3 friends on a first class. 5-star resort tour to play the 50 best golf courses in the world.", 150000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "A Kids Library", "Add a wing to your city's library devoted to young writers and artists. Art celebrities visit often to support your work.", 175000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "South Sea Island Fantasy", "Pampered in luxury for two full months. Relax, unwind in warm waters, deserted beaches, and romantic nights.", 100000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Capitalists' Peace Corps", "Set up entrepreneurial business schools in 3rd world nations. Instructors are business people donating their knowledge & time.", 200000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Cruise the Mediterranean on a Private Yacht", "Visit small harbors in Italy, France, and Greece for a month with 12 friends.", 100000f, null),
            new Position(Position.TYPES.CASHFLOW, "Ca$hflow Day", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "Mini-Farm in the City", "Create a hands-on farm eco-system for city kids to learn and care for animals & plants.", 150000f, null),
            new Position(Position.TYPES.OPPORTUNITY, "Buy a Forest", "XXXXXX", 200000f, null),
            new Position(Position.TYPES.DREAM, "African Photo Safari", "Take 6 friends on a wild safari, photographing the most exotic animals in the world. Enjoy 5-star luxury in your tent.", 100000f, null),
            new Position(Position.TYPES.MISFORTUNE, "Lawsuit!", "Pay <b>one half</b> your cash to defend yourself.", null, null),
    };
    public static final Position[] RAT_RACE = new Position[]{
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.DOODAD, "Doodad", null, null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.MISFORTUNE, "Charity", "Use 1 or 2 dice for next 3 turns if you donate 10% of Total Income", null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.CASHFLOW, "Pay Check", null, null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.MARKET, "Market", null, null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.DOODAD, "Doodad", null, null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.MISFORTUNE, "Baby", "Congratulations!\nAdd in your child expenses\n(limit 3 children per Player", null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.CASHFLOW, "Pay Check", null, null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.MARKET, "Market", null, null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.DOODAD, "Doodad", null, null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.MISFORTUNE, "Downsized", "Pay amount of total expenses to the bank.\n<b>Lose 2 Turns</b>", null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.CASHFLOW, "Pay Check", null, null, null),
            new Position(Position.TYPES.OPPORTUNITY, "Opportunity", "Big/Small Deal", null, null),
            new Position(Position.TYPES.MARKET, "Market", null, null, null),
    };
}
