CREATE TABLE board_position
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    position INTEGER,
    CONSTRAINT pk_boardposition PRIMARY KEY (id)
);

CREATE TABLE board_position_pieces
(
    board_position_id BIGINT NOT NULL,
    set               VARCHAR(255),
    type              VARCHAR(255)
);

CREATE TABLE deck
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    card_indices       VARCHAR(255),
    current_card_index INTEGER,
    card_type          VARCHAR(255),
    CONSTRAINT pk_deck PRIMARY KEY (id)
);

CREATE TABLE game
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    big_deals_id    BIGINT,
    small_deals_id  BIGINT,
    market_cards_id BIGINT,
    doodads_id      BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    last_played     TIMESTAMP WITHOUT TIME ZONE,
    is_game_over    BOOLEAN,
    settings_id     BIGINT,
    turn_state_id   BIGINT,
    CONSTRAINT pk_game PRIMARY KEY (id)
);

CREATE TABLE game_fast_track
(
    game_id       BIGINT NOT NULL,
    fast_track_id BIGINT NOT NULL
);

CREATE TABLE game_players
(
    game_id    BIGINT NOT NULL,
    players_id BIGINT NOT NULL
);

CREATE TABLE game_rat_race
(
    game_id     BIGINT NOT NULL,
    rat_race_id BIGINT NOT NULL
);

CREATE TABLE game_setting
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    max_children          INTEGER,
    max_downsize          INTEGER,
    first_place_only      BOOLEAN,
    starting_paychecks    INTEGER,
    careers_dealt         INTEGER,
    max_doodad_cost       INTEGER,
    rat_race_only         BOOLEAN,
    dream_required        BOOLEAN,
    ft_business_exclusive BOOLEAN,
    force_escape_rat_race BOOLEAN,
    CONSTRAINT pk_gamesetting PRIMARY KEY (id)
);

CREATE TABLE player
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_id    BIGINT,
    has_won       BOOLEAN,
    is_active     BOOLEAN,
    color         VARCHAR(255),
    cash          FLOAT,
    career        VARCHAR(255),
    children      INTEGER,
    turns_lost    INTEGER,
    turns_charity INTEGER,
    on_fast_track BOOLEAN,
    dream_name    OID,
    taxes         FLOAT,
    mortgage      FLOAT,
    school        FLOAT,
    car           FLOAT,
    credit        FLOAT,
    retail        FLOAT,
    other         FLOAT,
    child         FLOAT,
    CONSTRAINT pk_player PRIMARY KEY (id)
);

CREATE TABLE player_assets
(
    player_id       BIGINT NOT NULL,
    name            OID,
    type            VARCHAR(255),
    sub_type        VARCHAR(255),
    count           FLOAT,
    down            FLOAT,
    cost            FLOAT,
    liability_type  VARCHAR(255),
    liability_name  OID,
    liability_value FLOAT,
    cashflow        FLOAT
);

CREATE TABLE player_liabilities
(
    player_id BIGINT NOT NULL,
    type      VARCHAR(255),
    name      OID,
    value     FLOAT
);

CREATE TABLE profile
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                            VARCHAR(255),
    speed                           SMALLINT,
    show_hints                      BOOLEAN,
    auto_select_opportunity_by_cash FLOAT,
    net_worth                       DOUBLE PRECISION,
    games_played                    INTEGER,
    games_won                       INTEGER,
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

CREATE TABLE profile_friends
(
    profile_id BIGINT NOT NULL,
    friends_id BIGINT NOT NULL
);

CREATE TABLE profile_games
(
    profile_id BIGINT NOT NULL,
    games_id   BIGINT NOT NULL
);

CREATE TABLE sale
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    deadline   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_sale PRIMARY KEY (id)
);

CREATE TABLE sale_offers
(
    sale_id   BIGINT NOT NULL,
    offer     FLOAT,
    player_id BIGINT NOT NULL,
    CONSTRAINT pk_sale_offers PRIMARY KEY (sale_id, player_id)
);

CREATE TABLE turn_state
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    current_player     INTEGER,
    player_has_moved   BOOLEAN,
    event_has_resolved BOOLEAN,
    sale_is_active     BOOLEAN,
    sale_id            BIGINT,
    CONSTRAINT pk_turnstate PRIMARY KEY (id)
);

ALTER TABLE game
    ADD CONSTRAINT uc_game_bigdeals UNIQUE (big_deals_id);

ALTER TABLE game
    ADD CONSTRAINT uc_game_doodads UNIQUE (doodads_id);

ALTER TABLE game_fast_track
    ADD CONSTRAINT uc_game_fast_track_fasttrack UNIQUE (fast_track_id);

ALTER TABLE game
    ADD CONSTRAINT uc_game_marketcards UNIQUE (market_cards_id);

ALTER TABLE game_players
    ADD CONSTRAINT uc_game_players_players UNIQUE (players_id);

ALTER TABLE game_rat_race
    ADD CONSTRAINT uc_game_rat_race_ratrace UNIQUE (rat_race_id);

ALTER TABLE game
    ADD CONSTRAINT uc_game_settings UNIQUE (settings_id);

ALTER TABLE game
    ADD CONSTRAINT uc_game_smalldeals UNIQUE (small_deals_id);

ALTER TABLE game
    ADD CONSTRAINT uc_game_turnstate UNIQUE (turn_state_id);

ALTER TABLE turn_state
    ADD CONSTRAINT uc_turnstate_sale UNIQUE (sale_id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_BIGDEALS FOREIGN KEY (big_deals_id) REFERENCES deck (id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_DOODADS FOREIGN KEY (doodads_id) REFERENCES deck (id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_MARKETCARDS FOREIGN KEY (market_cards_id) REFERENCES deck (id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_SETTINGS FOREIGN KEY (settings_id) REFERENCES game_setting (id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_SMALLDEALS FOREIGN KEY (small_deals_id) REFERENCES deck (id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_TURNSTATE FOREIGN KEY (turn_state_id) REFERENCES turn_state (id);

ALTER TABLE turn_state
    ADD CONSTRAINT FK_TURNSTATE_ON_SALE FOREIGN KEY (sale_id) REFERENCES sale (id);

ALTER TABLE board_position_pieces
    ADD CONSTRAINT fk_boardposition_pieces_on_board_position FOREIGN KEY (board_position_id) REFERENCES board_position (id);

ALTER TABLE game_fast_track
    ADD CONSTRAINT fk_gamfastra_on_board_position FOREIGN KEY (fast_track_id) REFERENCES board_position (id);

ALTER TABLE game_fast_track
    ADD CONSTRAINT fk_gamfastra_on_game FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE game_players
    ADD CONSTRAINT fk_gampla_on_game FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE game_players
    ADD CONSTRAINT fk_gampla_on_player FOREIGN KEY (players_id) REFERENCES player (id);

ALTER TABLE game_rat_race
    ADD CONSTRAINT fk_gamratrac_on_board_position FOREIGN KEY (rat_race_id) REFERENCES board_position (id);

ALTER TABLE game_rat_race
    ADD CONSTRAINT fk_gamratrac_on_game FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE player_assets
    ADD CONSTRAINT fk_player_assets_on_player FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE player_liabilities
    ADD CONSTRAINT fk_player_liabilities_on_player FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE profile_friends
    ADD CONSTRAINT fk_profri_on_friends FOREIGN KEY (friends_id) REFERENCES profile (id);

ALTER TABLE profile_friends
    ADD CONSTRAINT fk_profri_on_profile FOREIGN KEY (profile_id) REFERENCES profile (id);

ALTER TABLE profile_games
    ADD CONSTRAINT fk_progam_on_game FOREIGN KEY (games_id) REFERENCES game (id);

ALTER TABLE profile_games
    ADD CONSTRAINT fk_progam_on_profile FOREIGN KEY (profile_id) REFERENCES profile (id);

ALTER TABLE sale_offers
    ADD CONSTRAINT fk_sale_offers_on_sale FOREIGN KEY (sale_id) REFERENCES sale (id);