spring:
  application:
    name: cashflow

  datasource:
    url: jdbc:postgresql://localhost:5428/cashflow
    driver-class-name: org.postgresql.Driver
    username: cashflow_dev
    password: secure-p@sswords-R-long
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080